### ISSUE TITLE
Amazing theme

### ISSUE THREAD

**Issue by evertjr** [yume-theme/yume-vscode#1]
Every once in a while I try to find a nice looking Xcode theme for vscode and this is absolutely amazing.

Just a few suggestions for improvements to make it perfect:

- Use different colors for React components and html (in JSX/TSX files).
<img width="187" alt="image" src="https://github.com/yume-theme/yume-vscode/assets/13040196/0586797c-5860-4fe5-a634-ce4d7d35bd0e">

- Make the selection highlight less opaque, it's currently a little hard to see
<img width="167" alt="image" src="https://github.com/yume-theme/yume-vscode/assets/13040196/a7c8cea8-228f-477e-b5dc-89c864fe1057">

- Make the autocomplete and other popups stand out a little from the background color 
<img width="280" alt="image" src="https://github.com/yume-theme/yume-vscode/assets/13040196/257b7550-2840-440f-98ff-17a059b2cc34">

Thank you for the effort put in this theme, it's very tastefully done.

**Comment by feelthatvib3** [comment]
Greetings, @evertjr! 👋

I want to express my gratitude for your valuable feedback and kind words regarding the theme. It really serves as a great source of inspiration and motivation to keep the project maintained. I appreciate the suggestions you've made and will work diligently to address the issues you've encountered.

Thank you so much once again for the feedback, I hope you have the best possible user experience while using the theme Cheers! 💖
